/*
 * Audio Player HTML5 v3.0
 *
 * Copyright 2012-2018, LambertGroup
 *
 */

 (function(d){function C(a){a=document.getElementById(a.audioID);return!(!a.canPlayType||!a.canPlayType("audio/mpeg;").replace(/no/,""))}function L(a){var c=navigator.userAgent;if(c.match(/iPad/i)||c.match(/iPhone/i)){a.userOS="iOS";var d=c.indexOf("OS ")}else c.match(/Android/i)?(a.userOS="Android",d=c.indexOf("Android ")):a.userOS="unknown";a.userOSver="iOS"===a.userOS&&-1<d?c.substr(d+3,3).replace("_","."):"Android"===a.userOS&&-1<d?c.substr(d+8,3):"unknown"}function F(a,c,l,e,g,h,f,k,v,m,w,t,p,
 x){a.totalTime="Infinity";c.isSliderInitialized&&(v.slider("destroy"),c.isSliderInitialized=!1);c.isProgressInitialized&&(m.progressbar("destroy"),c.isProgressInitialized=!1);a.is_changeSrc=!0;a.is_buffer_complete=!1;t.width(a.audioPlayerWidth);m.css({background:c.bufferEmptyColor});a.curSongText="";c.showAuthor&&null!=a.playlist_arr[a.current_img_no].author&&""!=a.playlist_arr[a.current_img_no].author&&(a.curSongText+=a.playlist_arr[a.current_img_no].author+" - ");c.showTitle&&null!=a.playlist_arr[a.current_img_no].title&&
 ""!=a.playlist_arr[a.current_img_no].title&&(a.curSongText+=a.playlist_arr[a.current_img_no].title);a.isAuthorTitleInsideScrolling=!1;a.authorTitleInsideWait=0;p.stop();p.css({"margin-left":0});p.html(a.curSongText);a.curSongText||t.css({display:"none",width:0,height:0,padding:0,margin:0});f=document.getElementById(a.audioID);d(l[a.current_img_no]).css({background:c.playlistRecordBgOnColor,"border-bottom-color":c.playlistRecordBottomBorderOnColor,color:c.playlistRecordTextOnColor});G(-1,a,c,e,g,h);
 c=a.playlist_arr[a.current_img_no].sources_mp3;if(-1!=q.indexOf("opera")||-1!=q.indexOf("opr")||-1!=q.indexOf("firefox")||-1!=q.indexOf("mozzila"))c=a.playlist_arr[a.current_img_no].sources_ogg,""!=C(a)&&(c=a.playlist_arr[a.current_img_no].sources_mp3);if(-1!=q.indexOf("chrome")||-1!=q.indexOf("msie")||-1!=q.indexOf("safari"))c=a.playlist_arr[a.current_img_no].sources_mp3,-1!=q.indexOf("opr")&&(c=a.playlist_arr[a.current_img_no].sources_ogg,""!=C(a)&&(c=a.playlist_arr[a.current_img_no].sources_mp3));
 -1!=q.indexOf("android")&&(c=a.playlist_arr[a.current_img_no].sources_mp3);"iOS"===a.userOS&&(c=a.playlist_arr[a.current_img_no].sources_mp3);f.src=c;document.getElementById(a.audioID).load()}function r(a){var c=10>Math.floor(a/60)?"0"+Math.floor(a/60):Math.floor(a/60);return c+":"+(10>Math.floor(a-60*c)?"0"+Math.floor(a-60*c):Math.floor(a-60*c))}function I(a,c,l,e,g,h,f,k){a.is_changeSrc=!1;a.is_very_first&&(a.is_very_first=!1);g.width(a.audioPlayerWidth);e.width(a.audioPlayerWidth);e.slider({value:0,
 step:.01,orientation:"horizontal",range:"min",max:a.totalTime,slide:function(){a.is_seeking=!0},stop:function(c,e){a.is_seeking=!1;document.getElementById(a.audioID).currentTime=e.value;0!=document.getElementById(a.audioID).paused&&(document.getElementById(a.audioID).play(),f.addClass("AudioPause"))},create:function(a,e){c.isSliderInitialized=!0}});d(".ui-slider-range",e).css({background:c.seekbarColor});g.progressbar({value:0,complete:function(){a.is_buffer_complete=!0},create:function(a,e){c.isProgressInitialized=
 !0}});d(".ui-widget-header",g).css({background:c.bufferFullColor})}function M(a,c,d,e,g,h,f,k,v,m){!a.isAuthorTitleInsideScrolling&&5<=a.authorTitleInsideWait&&m.width()>a.audioPlayerWidth?(a.isAuthorTitleInsideScrolling=!0,a.authorTitleInsideWait=0,m.html(a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "+a.curSongText+" **** "),m.css({"margin-left":0}),m.stop().animate({"margin-left":a.audioPlayerWidth-m.width()+"px"},parseInt(1E4*(m.width()-a.audioPlayerWidth)/
 150,10),"linear",function(){a.isAuthorTitleInsideScrolling=!1})):!a.isAuthorTitleInsideScrolling&&m.width()>a.audioPlayerWidth&&a.authorTitleInsideWait++;curTime=document.getElementById(a.audioID).currentTime;bufferedTime=0;a.is_changeSrc&&!isNaN(a.totalTime)&&"Infinity"!=a.totalTime&&I(a,c,d,e,g,h,f,k);!a.is_seeking&&c.isSliderInitialized&&e.slider("value",curTime);-1!=q.indexOf("android")?(a.totalTime!=document.getElementById(a.audioID).duration&&0<document.getElementById(a.audioID).duration&&(a.totalTime=
 document.getElementById(a.audioID).duration,c.isSliderInitialized&&(e.slider("destroy"),c.isSliderInitialized=!1),c.isProgressInitialized&&(g.progressbar("destroy"),c.isProgressInitialized=!1),I(a,c,d,e,g,h,f,k)),g.css({background:c.bufferFullColor}),isNaN(a.totalTime)||"Infinity"==a.totalTime?h.text("00:00 / "+r(0)):h.text(r(curTime)+" / "+r(a.totalTime))):(document.getElementById(a.audioID).buffered.length&&(bufferedTime=document.getElementById(a.audioID).buffered.end(document.getElementById(a.audioID).buffered.length-
 1),0<bufferedTime&&!a.is_buffer_complete&&!isNaN(a.totalTime)&&"Infinity"!=a.totalTime&&c.isProgressInitialized&&g.progressbar({value:100*bufferedTime/a.totalTime})),isNaN(a.totalTime)||"Infinity"==a.totalTime?h.text(r(curTime)+" / "+r(bufferedTime)):h.text(r(curTime)+" / "+r(a.totalTime)));x(c,"cookie_timePlayed",curTime)}function G(a,c,l,e,g,h){if(c.total_images>l.numberOfThumbsPerScreen){var f=(e.height()+1)*(c.total_images-l.numberOfThumbsPerScreen),k=0;h.stop(!0,!0);d("html, body").off("touchstart touchmove").on("touchstart touchmove",
 function(a){a.preventDefault()});-1==a||c.isCarouselScrolling?!c.isCarouselScrolling&&c.total_images>l.numberOfThumbsPerScreen&&(c.isCarouselScrolling=!0,k=-1*parseInt((e.height()+1)*c.current_img_no,10),Math.abs(k)>f&&(k=-1*f),c.total_images>l.numberOfThumbsPerScreen&&l.showPlaylist&&g.slider("value",100+parseInt(100*k/f)),h.animate({top:k+"px"},500,"easeOutCubic",function(){c.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})})):(c.isCarouselScrolling=
 !0,1>=a&&(a=0),k=2>=a?-1*f:parseInt(f*(a-100)/100,10),0<k&&(k=0),h.animate({top:k+"px"},1100,"easeOutQuad",function(){c.isCarouselScrolling=!1;d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){})}))}}function x(a,c,d,e){a.continuouslyPlayOnAllPages&&(a=new Date,a.setDate(a.getDate()+e),d=escape(d)+(null==e?"":"; expires="+a.toUTCString())+";path=/",document.cookie=c+"="+d)}function D(a,c){if(a.continuouslyPlayOnAllPages){var d,e=document.cookie.split(";");for(d=0;d<
 e.length;d++){var g=e[d].substr(0,e[d].indexOf("="));var h=e[d].substr(e[d].indexOf("=")+1);g=g.replace(/^\s+|\s+$/g,"");if(g==c)return unescape(h)}}}function J(a,c){var d=Math.ceil(Math.random()*(c.total_images-1));c.current_img_no=d!=c.current_img_no?d:Math.ceil(Math.random()*(c.total_images-1))}function N(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}function K(){d("audio").each(function(){d(".AudioPlay").removeClass("AudioPause");
 d(this)[0].pause()})}var q=navigator.userAgent.toLowerCase();d.fn.audio1_html5=function(a){a=d.extend({},d.fn.audio1_html5.defaults,a);return this.each(function(){var c=d(this),l=d('<div class="AudioControls"> <a class="AudioRewind" title="Rewind"></a><a class="AudioPlay" title="Play/Pause"></a><a class="AudioPrev" title="Previous"></a><a class="AudioNext" title="Next"></a><a class="AudioShowHidePlaylist" title="Show/Hide Playlist"></a><a class="VolumeButton" title="Mute/Unmute"></a><div class="VolumeSlider"></div> <div class="AudioTimer">00:00 / 00:00</div>  </div>   <div class="AudioBuffer"></div><div class="AudioSeek"></div><div class="songAuthorTitle"><div class="songAuthorTitleInside">AA</div></div>    <div class="thumbsHolderWrapper"><div class="playlistPadding"><div class="thumbsHolderVisibleWrapper"><div class="thumbsHolder"></div></div></div></div>  <div class="slider-vertical"></div>'),
 e=c.parent(".audio1_html5"),g=d(this).parent();e.addClass(a.skin);e.append(l);var h=d(".AudioControls",e);l=d(".AudioRewind",e);var f=d(".AudioPlay",e),k=d(".AudioPrev",e),v=d(".AudioNext",e),m=d(".AudioShowHidePlaylist",e),w=d(".VolumeButton",e),t=d(".VolumeSlider",e),p=d(".AudioTimer",e),r=d(".songAuthorTitle",e),E=d(".songAuthorTitleInside",e),z=d(".AudioBuffer",e),B=d(".AudioSeek",e);e.wrap("<div class='the_wrapper'></div>");var C=e.parent();N();e.css({background:a.playerBg,padding:a.playerPadding+
 "px"});var b={current_img_no:0,is_very_first:!0,total_images:0,is_seeking:!1,is_changeSrc:!1,is_buffer_complete:!1,timeupdateInterval:"",totalTime:"",playlist_arr:"",isCarouselScrolling:!1,isAuthorTitleInsideScrolling:!1,curSongText:"",authorTitleInsideWait:0,audioPlayerWidth:0,audioPlayerHeight:0,audioID:"",audioObj:"",cookie_timePlayed:0,cookie_current_img_no:0,cookie_initialVolume:0,cookie_muteVolume:0,cookie_autoPlay:!1,userOS:"",userOSver:0};b.audioID=c.attr("id");-1==(-1==navigator.userAgent.indexOf("Opera")&&
 navigator.userAgent.indexOf("OPR"))&&(-1!=navigator.userAgent.indexOf("Chrome")&&-1!=navigator.vendor.indexOf("Google")&&(a.autoPlay=!1),-1!=navigator.userAgent.indexOf("Safari")&&-1!=navigator.vendor.indexOf("Apple")&&-1==navigator.platform.indexOf("Win")&&(a.autoPlay=!1));L(b);"iOS"===b.userOS&&e.css({"padding-top":"0px"});b.audioPlayerWidth=0;a.showRewindBut?b.audioPlayerWidth+=l.width()+parseInt(l.css("margin-left").substring(0,l.css("margin-left").length-2))+parseInt(l.css("margin-right").substring(0,
 l.css("margin-right").length-2)):l.css({display:"none",width:0,height:0,padding:0,margin:0});a.showPlayBut?b.audioPlayerWidth+=f.width()+parseInt(f.css("margin-left").substring(0,f.css("margin-left").length-2))+parseInt(f.css("margin-right").substring(0,f.css("margin-right").length-2)):f.css({display:"none",width:0,height:0,padding:0,margin:0});a.showPreviousBut?b.audioPlayerWidth+=k.width()+parseInt(k.css("margin-left").substring(0,k.css("margin-left").length-2))+parseInt(k.css("margin-right").substring(0,
 k.css("margin-right").length-2)):k.css({display:"none",width:0,height:0,padding:0,margin:0});a.showNextBut?b.audioPlayerWidth+=v.width()+parseInt(v.css("margin-left").substring(0,v.css("margin-left").length-2))+parseInt(v.css("margin-right").substring(0,v.css("margin-right").length-2)):v.css({display:"none",width:0,height:0,padding:0,margin:0});a.showPlaylistBut?b.audioPlayerWidth+=m.width()+parseInt(m.css("margin-left").substring(0,m.css("margin-left").length-2))+parseInt(m.css("margin-right").substring(0,
 m.css("margin-right").length-2)):m.css({display:"none",width:0,height:0,padding:0,margin:0});a.showVolumeBut?b.audioPlayerWidth+=w.width()+parseInt(w.css("margin-left").substring(0,w.css("margin-left").length-2))+parseInt(w.css("margin-right").substring(0,w.css("margin-right").length-2)):w.css({display:"none",width:0,height:0,padding:0,margin:0});a.showVolumeSliderBut?b.audioPlayerWidth+=t.width()+parseInt(t.css("margin-left").substring(0,t.css("margin-left").length-2))+parseInt(t.css("margin-right").substring(0,
 t.css("margin-right").length-2)):t.css({display:"none",width:0,height:0,padding:0,margin:0});a.showTimer?b.audioPlayerWidth+=p.width()+parseInt(p.css("margin-left").substring(0,p.css("margin-left").length-2))+parseInt(p.css("margin-right").substring(0,p.css("margin-right").length-2)):p.css({display:"none",width:0,height:0,padding:0,margin:0});a.showSeekBar||(z.css({display:"none",width:0,height:0,padding:0,margin:0}),B.css({display:"none",width:0,height:0,padding:0,margin:0}));p.css({color:a.timerColor});
 r.css({color:a.songAuthorTitleColor});"iOS"===b.userOS?8>Number(b.userOSver)&&(b.audioPlayerWidth-=9):b.audioPlayerWidth-=9;-1!=q.indexOf("android")?a.playlistTopPos-=0:"iOS"===b.userOS&&(8>Number(b.userOSver)?h.css("margin-top","-9px"):h.css("margin-top","6px"),a.playlistTopPos-=5);g.width(b.audioPlayerWidth+10);a.showSeekBar||g.height(e.height()-4);a.showAuthor||a.showTitle||g.height(e.height()-22);b.audioPlayerHeight=e.height()+2*a.playerPadding;var u=d(".thumbsHolderWrapper",e);g=d(".playlistPadding",
 e);h=d(".thumbsHolderVisibleWrapper",e);var A=d(".thumbsHolder",e),n=d(".slider-vertical",e);a.showPlaylist||u.css({display:"none"});a.showPlaylistOnInit||u.css({opacity:0,"margin-top":"-20px",display:"none"});u.css({width:e.width()+2*a.playerPadding+"px",top:b.audioPlayerHeight+a.playlistTopPos+"px",left:"0px",background:a.playlistBgColor});h.width(e.width()+1+2*a.playerPadding);b.playlist_arr=[];d(".xaudioplaylist",e).children().each(function(){currentElement=d(this);b.total_images++;b.playlist_arr[b.total_images-
 1]=[];b.playlist_arr[b.total_images-1].title="";b.playlist_arr[b.total_images-1].author="";b.playlist_arr[b.total_images-1].thumb="";b.playlist_arr[b.total_images-1].sources_mp3="";b.playlist_arr[b.total_images-1].sources_ogg="";null!=currentElement.find(".xtitle").html()&&(b.playlist_arr[b.total_images-1].title=currentElement.find(".xtitle").html());null!=currentElement.find(".xauthor").html()&&(b.playlist_arr[b.total_images-1].author=currentElement.find(".xauthor").html());null!=currentElement.find(".xthumb").html()&&
 (b.playlist_arr[b.total_images-1].thumb=currentElement.find(".xthumb").html());null!=currentElement.find(".xsources_mp3").html()&&(b.playlist_arr[b.total_images-1].sources_mp3=currentElement.find(".xsources_mp3").html());null!=currentElement.find(".xsources_ogg").html()&&(b.playlist_arr[b.total_images-1].sources_ogg=currentElement.find(".xsources_ogg").html());thumbsHolder_Thumb=d('<div class="thumbsHolder_ThumbOFF" rel="'+(b.total_images-1)+'"><div class="padding">'+(a.showPlaylistNumber?b.total_images+
 ". ":"")+b.playlist_arr[b.total_images-1].title+"</div></div>");A.append(thumbsHolder_Thumb);thumbsHolder_Thumb.css({top:(thumbsHolder_Thumb.height()+1)*b.total_images+"px",background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor});1!==b.total_images||a.shuffle||thumbsHolder_Thumb.css({background:a.playlistRecordBgOnColor,"border-bottom-color":a.playlistRecordBottomBorderOnColor,color:a.playlistRecordTextOnColor})});u.height(2*
 a.playlistPadding+(thumbsHolder_Thumb.height()+1)*(a.numberOfThumbsPerScreen<b.total_images?a.numberOfThumbsPerScreen:b.total_images));h.height((thumbsHolder_Thumb.height()+1)*(a.numberOfThumbsPerScreen<b.total_images?a.numberOfThumbsPerScreen:b.total_images));g.css({padding:a.playlistPadding+"px"});var H=a.showPlaylist&&a.showPlaylistOnInit?b.audioPlayerHeight+u.height()+a.playlistTopPos:b.audioPlayerHeight;C.css({width:e.width()+2*a.playerPadding+"px",height:H+"px"});b.total_images>a.numberOfThumbsPerScreen&&
 a.showPlaylist?(n.slider({orientation:"vertical",range:"min",min:1,max:100,step:1,value:100,slide:function(c,d){G(d.value,b,a,thumbsHolder_Thumb,n,A)}}),n.css({display:"inline",position:"absolute",height:u.height()-16-2*a.playlistPadding+"px",left:e.width()+2*a.playerPadding-n.width()-a.playlistPadding+"px",top:b.audioPlayerHeight+a.playlistTopPos+a.playlistPadding+"px"}),a.showPlaylistOnInit||n.css({opacity:0,display:"none"}),d(".thumbsHolder_ThumbOFF",e).css({width:e.width()+2*a.playerPadding-n.width()-
 3*a.playlistPadding+"px"})):d(".thumbsHolder_ThumbOFF",e).css({width:e.width()+2*a.playerPadding-2*a.playlistPadding+"px"});h.mousewheel(function(c,d,e,f){c.preventDefault();c=n.slider("value");if(1<parseInt(c)&&-1==parseInt(d)||100>parseInt(c)&&1==parseInt(d))c+=d,n.slider("value",c),G(c,b,a,thumbsHolder_Thumb,n,A)});var y=d(".thumbsHolder_ThumbOFF",e);y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor});y.click(function(){if(!b.is_changeSrc){a.autoPlay=
 !0;var g=d(this).attr("rel");y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor});b.current_img_no=g;x(a,"cookie_current_img_no",b.current_img_no);F(b,a,y,thumbsHolder_Thumb,n,A,e,f,B,z,p,r,E,c)}});y.mouseover(function(){d(this).css({background:a.playlistRecordBgOnColor,"border-bottom-color":a.playlistRecordBottomBorderOnColor,color:a.playlistRecordTextOnColor})});y.mouseout(function(){var c=d(this),e=c.attr("rel");
 b.current_img_no!=e&&c.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor})});b.cookie_initialVolume=D(a,"cookie_initialVolume");b.cookie_initialVolume&&(a.initialVolume=b.cookie_initialVolume);t.slider({value:a.initialVolume,step:.05,orientation:"horizontal",range:"min",max:1,animate:!0,slide:function(c,d){document.getElementById(b.audioID).volume=d.value;x(a,"cookie_initialVolume",d.value)},stop:function(a,b){}});
 document.getElementById(b.audioID).volume=a.initialVolume;t.css({background:a.volumeOffColor});d(".ui-slider-range",t).css({background:a.volumeOnColor});f.click(function(){var c=document.getElementById(b.audioID).paused;K();0==c?(document.getElementById(b.audioID).pause(),f.removeClass("AudioPause"),x(a,"cookie_autoPlay",!1)):(document.getElementById(b.audioID).play(),f.addClass("AudioPause"),x(a,"cookie_autoPlay",!0))});l.click(function(){document.getElementById(b.audioID).currentTime=0;K();document.getElementById(b.audioID).play();
 f.addClass("AudioPause");f.addClass("AudioPause")});v.click(function(){if(!b.is_changeSrc||b.is_very_first)a.autoPlay=!0,y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),a.shuffle?J(a,b):b.current_img_no==b.total_images-1?b.current_img_no=0:b.current_img_no++,x(a,"cookie_current_img_no",b.current_img_no),F(b,a,y,thumbsHolder_Thumb,n,A,e,f,B,z,p,r,E,c)});k.click(function(){if(!b.is_changeSrc||b.is_very_first)a.autoPlay=
 !0,y.css({background:a.playlistRecordBgOffColor,"border-bottom-color":a.playlistRecordBottomBorderOffColor,color:a.playlistRecordTextOffColor}),a.shuffle?J(a,b):0>b.current_img_no-1?b.current_img_no=b.total_images-1:b.current_img_no--,x(a,"cookie_current_img_no",b.current_img_no),F(b,a,y,thumbsHolder_Thumb,n,A,e,f,B,z,p,r,E,c)});m.click(function(){0>u.css("margin-top").substring(0,u.css("margin-top").length-2)?(aux_opacity=1,aux_display="block",aux_margin_top="0px",H=b.audioPlayerHeight+u.height()+
 a.playlistTopPos,u.css({display:aux_display}),b.total_images>a.numberOfThumbsPerScreen&&n.css({opacity:1,display:"block"})):(aux_opacity=0,aux_display="none",aux_margin_top="-20px",b.total_images>a.numberOfThumbsPerScreen&&n.css({opacity:0,display:"none"}),H=b.audioPlayerHeight);u.animate({opacity:aux_opacity,"margin-top":aux_margin_top},500,"easeOutQuad",function(){u.css({display:aux_display})});C.animate({height:H},500,"easeOutQuad",function(){})});w.click(function(){document.getElementById(b.audioID).muted?
 (document.getElementById(b.audioID).muted=!1,w.removeClass("VolumeButtonMuted"),x(a,"cookie_muteVolume",0)):(document.getElementById(b.audioID).muted=!0,w.addClass("VolumeButtonMuted"),x(a,"cookie_muteVolume",1))});A.swipe({swipeStatus:function(c,e,f,g,h,k){"up"!=f&&"down"!=f||0==g||(currentScrollVal=n.slider("value"),currentScrollVal="up"==f?currentScrollVal-1.5:currentScrollVal+1.5,n.slider("value",currentScrollVal),d("html, body").off("touchstart touchmove").on("touchstart touchmove",function(a){a.preventDefault()}),
 G(currentScrollVal,b,a,thumbsHolder_Thumb,n,A))},threshold:100,maxTimeThreshold:500,fingers:"all"});document.getElementById(b.audioID).addEventListener("ended",function(){a.loop?v.click():d(".AudioPlay").removeClass("AudioPause")});b.cookie_timePlayed=D(a,"cookie_timePlayed");b.cookie_current_img_no=D(a,"cookie_current_img_no");b.cookie_autoPlay=D(a,"cookie_autoPlay");void 0!=b.cookie_current_img_no?b.current_img_no=b.cookie_current_img_no:a.shuffle&&J(a,b);a.continuouslyPlayOnAllPages&&x(a,"cookie_current_img_no",
 b.current_img_no);void 0!=b.cookie_autoPlay&&(a.autoPlay="true"==b.cookie_autoPlay?!0:!1);if(-1!=q.indexOf("ipad")||-1!=q.indexOf("iphone")||-1!=q.indexOf("ipod")||-1!=q.indexOf("webos")||-1!=q.indexOf("android"))a.autoPlay=!1;F(b,a,y,thumbsHolder_Thumb,n,A,e,f,B,z,p,r,E,c);b.cookie_muteVolume=D(a,"cookie_muteVolume");1<=b.cookie_muteVolume&&w.click();b.timeupdateInterval=setInterval(function(){M(b,a,e,B,z,p,f,c,r,E)},300);document.getElementById(b.audioID).addEventListener("durationchange",function(){b.is_changeSrc&&
 (b.totalTime=document.getElementById(b.audioID).duration)});document.getElementById(b.audioID).addEventListener("canplay",function(){b.cookie_timePlayed&&(document.getElementById(b.audioID).currentTime=b.cookie_timePlayed,b.cookie_timePlayed=null);"iOS"===b.userOS&&b.totalTime!=document.getElementById(b.audioID).duration&&(a.isSliderInitialized&&(B.slider("destroy"),a.isSliderInitialized=!1),a.isProgressInitialized&&(z.progressbar("destroy"),a.isProgressInitialized=!1),b.totalTime=document.getElementById(b.audioID).duration,
 I(b,a,e,B,z,p,f,c),a.isProgressInitialized&&z.progressbar({value:b.audioPlayerWidth}));-1!=q.indexOf("opera")||("iOS"===b.userOS||"Android"===b.userOS)&&b.is_very_first||(a.autoPlay?(K(),document.getElementById(b.audioID).play(),f.addClass("AudioPause")):0===document.getElementById(b.audioID).currentTime&&f.removeClass("AudioPause"))})})};d.fn.audio1_html5.defaults={skin:"whiteControllers",initialVolume:.5,autoPlay:!1,loop:!0,shuffle:!1,playerPadding:5,playerBg:"#000000",bufferEmptyColor:"#929292",
 bufferFullColor:"#454545",seekbarColor:"#ffffff",volumeOffColor:"#454545",volumeOnColor:"#ffffff",timerColor:"#ffffff",songAuthorTitleColor:"#fffff",showRewindBut:!0,showPlayBut:!0,showPreviousBut:!0,showNextBut:!0,showPlaylistBut:!0,showVolumeBut:!0,showVolumeSliderBut:!0,showTimer:!0,showSeekBar:!0,showAuthor:!0,showTitle:!0,showPlaylist:!0,showPlaylistOnInit:!0,playlistTopPos:2,playlistBgColor:"#000000",playlistRecordBgOffColor:"#000000",playlistRecordBgOnColor:"#333333",playlistRecordBottomBorderOffColor:"#333333",
 playlistRecordBottomBorderOnColor:"#FFFFFF",playlistRecordTextOffColor:"#777777",playlistRecordTextOnColor:"#FFFFFF",numberOfThumbsPerScreen:7,playlistPadding:4,showPlaylistNumber:!0,continuouslyPlayOnAllPages:!1,isSliderInitialized:!1,isProgressInitialized:!1}})(jQuery);
